### ISSUE TITLE
which sites allows "upload lulz.php " ?

### ISSUE THREAD

**Issue by minanagehsalalma** [ScRiPt1337/Lulzwiper-Ransomware#1]
are you talking about the free web hosting sites ?

**Comment by ScRiPt1337** [comment]
No

**Comment by minanagehsalalma** [comment]
@ScRiPt1337  so what site are we talking about  ?

**Comment by ScRiPt1337** [comment]
you have to get admin access of any file any upload it using any upload or  upload it in any shelled server

**Comment by minanagehsalalma** [comment]
So it's post explosion-proof  thing .
